# Generated by Django 4.0.3 on 2022-03-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': True},
        ),
    ]
