# Generated by Django 4.0.3 on 2022-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_actor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AddField(
            model_name='actor',
            name='mid_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='test_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
