# Generated by Django 4.0.3 on 2022-03-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_actor_options_actor_mid_name_actor_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='mid_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='test_name',
        ),
    ]
