# Generated by Django 4.0.3 on 2022-03-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_actor_mid_name_remove_actor_test_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actorss',
        ),
    ]
