# Generated by Django 4.0.3 on 2022-03-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_actor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
    ]
